import { Hono } from "hono";
import { eq } from "drizzle-orm";
import { db } from "../db";
import { tests, variants, events } from "../db/schema";

const app = new Hono();

// CSV export
app.get("/:id/export/csv", async (c) => {
  const test = await db.query.tests.findFirst({
    where: eq(tests.id, c.req.param("id")),
    with: { variants: true },
  });
  if (!test) return c.json({ error: "Test not found" }, 404);

  const rows: string[] = [
    "variant_label,variant_subject,sent,opens,clicks,bounces,unsubscribes,open_rate,click_rate,bounce_rate",
  ];

  for (const v of test.variants) {
    const variantEvents = await db.query.events.findMany({ where: eq(events.variantId, v.id) });
    const sent = variantEvents.filter((e) => e.type === "send").length;
    const opens = variantEvents.filter((e) => e.type === "open").length;
    const clicks = variantEvents.filter((e) => e.type === "click").length;
    const bounces = variantEvents.filter((e) => e.type === "bounce").length;
    const unsubs = variantEvents.filter((e) => e.type === "unsubscribe").length;

    const openRate = sent > 0 ? (opens / sent * 100).toFixed(2) : "0.00";
    const clickRate = sent > 0 ? (clicks / sent * 100).toFixed(2) : "0.00";
    const bounceRate = sent > 0 ? (bounces / sent * 100).toFixed(2) : "0.00";

    rows.push(
      `"${v.label}","${v.subject}",${sent},${opens},${clicks},${bounces},${unsubs},${openRate},${clickRate},${bounceRate}`
    );
  }

  return new Response(rows.join("\n"), {
    headers: {
      "Content-Type": "text/csv",
      "Content-Disposition": `attachment; filename="${test.name.replace(/[^a-zA-Z0-9]/g, "_")}_analytics.csv"`,
    },
  });
});

// PDF export (returns HTML formatted for print - can be PDF'd by browser)
app.get("/:id/export/pdf", async (c) => {
  const test = await db.query.tests.findFirst({
    where: eq(tests.id, c.req.param("id")),
    with: { variants: true },
  });
  if (!test) return c.json({ error: "Test not found" }, 404);

  let variantRows = "";
  for (const v of test.variants) {
    const variantEvents = await db.query.events.findMany({ where: eq(events.variantId, v.id) });
    const sent = variantEvents.filter((e) => e.type === "send").length;
    const opens = variantEvents.filter((e) => e.type === "open").length;
    const clicks = variantEvents.filter((e) => e.type === "click").length;
    const bounces = variantEvents.filter((e) => e.type === "bounce").length;
    const openRate = sent > 0 ? (opens / sent * 100).toFixed(1) : "0.0";
    const clickRate = sent > 0 ? (clicks / sent * 100).toFixed(1) : "0.0";
    const bounceRate = sent > 0 ? (bounces / sent * 100).toFixed(1) : "0.0";

    variantRows += `<tr>
      <td>${v.label}</td><td>${v.subject}</td>
      <td>${sent}</td><td>${openRate}%</td><td>${clickRate}%</td><td>${bounceRate}%</td>
    </tr>`;
  }

  const html = `<!DOCTYPE html>
<html><head><title>${test.name} - Analytics Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; color: #1B1B18; }
  h1 { font-size: 24px; border-bottom: 2px solid #AD8B00; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #E4E2DF; }
  th { background: #F9F9F8; font-weight: 600; font-size: 12px; text-transform: uppercase; }
  .meta { color: #716F6C; font-size: 14px; }
  @media print { body { margin: 0; } }
</style></head>
<body>
  <h1>${test.name}</h1>
  <p class="meta">Status: ${test.status} &bull; Created: ${new Date(test.createdAt).toLocaleDateString()} &bull; Split: ${test.trafficSplit}</p>
  <table>
    <thead><tr><th>Variant</th><th>Subject</th><th>Sent</th><th>Open Rate</th><th>Click Rate</th><th>Bounce Rate</th></tr></thead>
    <tbody>${variantRows}</tbody>
  </table>
  <p class="meta">Generated by MailSplit on ${new Date().toLocaleDateString()}</p>
</body></html>`;

  return new Response(html, {
    headers: { "Content-Type": "text/html" },
  });
});

export default app;
